blank_issues_enabled: false
contact_links:
  - name: "💡 Discussions"
    url: https://github.com/indresh404/RankerHub/discussions
    about: Please ask questions, propose large features, or seek support in GitHub Discussions first!
