name: "❓ Question or Support"
description: "Ask a question, troubleshoot an issue, or get support"
title: "[Question]: "
labels: ["help wanted", "gssoc26", "NSoC'26", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Need help? Please ask! Remember to search past issues and GitHub Discussions first.
  - type: textarea
    id: question
    attributes:
      label: "What is your question?"
      description: "Ask your question clearly and provide context."
      placeholder: "e.g., How do I reset my local Firebase database seeds?"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: "Context / What have you tried?"
      description: "Describe what you are trying to achieve and any troubleshooting steps you've already taken."
      placeholder: "e.g., I tried running npm run db-seed, but it returns a Firestore authentication error..."
    validations:
      required: true
  - type: checkboxes
    id: checklists
    attributes:
      label: "Before submitting"
      description: "Please check all of the following requirements."
      options:
        - label: "I have read the [Contributing Guidelines](https://github.com/indresh404/RankerHub/blob/main/docs/CONTRIBUTING.md)"
          required: true
        - label: "I have checked for duplicate questions."
          required: true
